name: DeepSeek Code Review
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub

      - name: Get PR Diff
        id: get-diff
        run: |
          gh pr diff ${{ github.event.pull_request.number }} > diff.txt
          echo "DIFF_PATH=diff.txt" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run DeepSeek Review
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python deepseek_review.py

      - name: Post Comments
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            try {
              const comments = JSON.parse(fs.readFileSync('comments.json'));
              await Promise.all(comments.map(comment => 
                github.rest.pulls.createReviewComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  body: comment.comment,
                  path: comment.path,
                  line: comment.line,
                  commit_id: context.payload.pull_request.head.sha
                })
              ));
            } catch (error) {
              console.error('Yorum gönderilemedi:', error);
            }